from dgenerate.extras.kolors.pipelines.pipeline_kolors_inpainting import KolorsInpaintPipeline
from dgenerate.extras.kolors.pipelines.pipeline_controlnet_xl_kolors_img2img import KolorsControlNetImg2ImgPipeline
from dgenerate.extras.kolors.pipelines.pipeline_controlnet_xl_kolors import KolorsControlNetPipeline
from dgenerate.extras.kolors.pipelines.pipeline_controlnet_xl_kolors_inpaint import KolorsControlNetInpaintPipeline