from dgenerate.extras.ultraedit.pipeline_stablediffusion_3_instruct_pix2pix import StableDiffusion3InstructPix2PixPipeline
from dgenerate.extras.ultraedit.pipeline_stablediffusion_xl_instruct_pix2pix import StableDiffusionXLInstructPix2PixPipeline
from dgenerate.extras.ultraedit.pipeline_stablediffusion_instruct_pix2pix import StableDiffusionInstructPix2PixPipeline