FROM nvidia/cuda:12.6.1-runtime-ubuntu24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y python3 python3-pip python3-wheel python3-venv python3-tk sudo git
RUN useradd -ms /bin/bash dgenerate
RUN echo 'dgenerate:dgenerate' | chpasswd
RUN usermod -aG sudo dgenerate
RUN echo 'dgenerate ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER dgenerate
RUN git config --global --add safe.directory /opt/dgenerate
ENV DISPLAY=host.docker.internal:0.0
ENV PATH="/usr/local/cuda/bin:/home/dgenerate/.local/bin:$PATH"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
WORKDIR "/opt/dgenerate"