FROM nvidia/cuda:12.3.1-runtime-ubuntu22.04
RUN apt update && apt install -y python3.10 python3-pip python3-wheel
RUN ln -s /usr/local/cuda/lib64/libnvrtc.so.12 /usr/local/cuda/lib64/libnvrtc.so
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
ENV PATH=/usr/local/cuda/bin:/home/dgenerate/.local/bin:$PATH
RUN useradd -ms /bin/bash dgenerate
USER dgenerate
WORKDIR "/opt/dgenerate"