[tool.poetry]
name = "dgenerate"
version = "0.0.0"
description = "Stable diffusion batch image generation tool."
authors = ["Teriks <Teriks@users.noreply.github.com>"]
readme = "README.rst"
license = "BSD 3-Clause"

[tool.poetry.dependencies]
python = ">=3.10,<4"
diffusers = "0.31.0"
peft = "0.13.0"
transformers = "4.45.2"
accelerate = "1.0.1"
optimum-quanto = "0.2.5"
pytorch-lightning = "^2.4.0"
lightning-utilities = "^0.11.8"
lightning-fabric = "^2.4.0"
omegaconf = "^2.3.0"
requests = "^2.32.3"
av = "^13.1.0"
pillow = "^11.0.0"
jinja2 = "^3.1.4"
torch = { version = "2.5.0", source = "pytorch" }
torchvision = {version = "0.20.0", source = "pytorch"}
torchsde = "0.2.6"
fake-useragent = "1.5.1"
opencv-python-headless = "^4.10.0.84"
psutil = "^6.1.0"
sentencepiece = "^0.2.0"
ftfy = "^6.3.0"
beautifulsoup4 = "^4.12.3"
matplotlib = "^3.9.2"
filelock = "^3.16.1"
importlib_metadata = "^8.5.0"
scipy = "^1.14.1"
einops = "^0.8.0"
timm = "^0.6.7"
scikit-image = "^0.24.0"
numpy = "^2.1.2"
spandrel = "^0.4.0"
spandrel_extra_arches = "^0.2.0"
asteval = "^1.0.5"
pygments = "^2.18.0"
toml = "^0.10.2"
tklinenums = "^1.7.1"
pyrfc6266 = "^1.0.2"
protobuf = "^5.28.2"
compel = "^2.0.3"
lark = "^1.2.2"
controlnet_aux = "^0.0.9"
packaging = "^24.1"

[tool.poetry.scripts]
dgenerate = 'dgenerate.__init__:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu124/"
priority = "explicit"