[[operations]]
function = "cleanup.py:lowercase"

[[operations]]
pattern = "\\bcat\\b"
substitution = "dog"
ignore_case = true # optional (ignorecase also works)
multiline = false  # optional
dotall = false # optional
count = 0 # optional, 0 means replace all


[[operations]]
pattern = "\\bfeline\\b"
substitution = "canine"

[[operations]]
function = "cleanup.py:remove_periods"
